Yaman_CMS2/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # path("", views.post_list, name="post_list"),
    path("", views.PostListView.as_view(), name="post_list"),  # Blog Home Page
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>",
        views.post_detail,
        name="post_detail",
    ),  # Post URL
    path(
        "<int:post_id>/share/", views.post_share, name="post_share"
    ),  # Share Post to an eamil
]

Yaman_CMS2/blog/models.py
from django.db import models
from django.utils import timezone

# from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse


class PublishedManager(models.Manager):
    """Context manager to view only Published posts"""

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


# Create your models here.
class Post(models.Model):
    """Main Posts Model"""

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # The custom manager

    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

Yaman_CMS2/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    """Share Post with Email Form"""

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

Yaman_CMS2/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail

from .forms import EmailPostForm

from .models import Post


class PostListView(ListView):
    """List all the posts on home Blog page with Paginatioon"""

    queryset = Post.published.all()
    # model = Post
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"


# Create views here.
"""
def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html", {"page": page, "posts": posts})
"""


def post_detail(request, year, month, day, post):
    """View post detail based on Post URL"""
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    return render(request, "blog/post/detail.html", {"post": post})


def post_share(request, post_id):
    """A view for to share the post using email"""

    # Get the post by id
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields are passed.
            cd = form.cleaned_data

            # ... Sending the email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(subject, message, "admin@myblog.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )

Yaman_CMS2/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>
{% endblock %}

Yaman_CMS2/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Muhammad Yaman Ghaibeh{% endblock %}

{% block content %}
  <h1>Muhammad Yaman Ghaibeh</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}

Yaman_CMS2/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}